### ISSUE TITLE
Help with path in script

### ISSUE THREAD

**Issue by 7OH** [T3los/mRemoteNGOpenVPN#1]
Can You add path to openvpn-gui to script ?
Don't wanna add this to PATH in windows.
And cannot add in script - it show error 
"C:\Program : name "C:\Program" not recognized as cmdlet name...."

**Comment by T3los** [comment]
Hello mate,

I don't think i will update the git to include the choice between using the PATH variable or including the exe path in the script. For now, at least. 

However, if you don't want to use the PATH, you can replace : 
```ps1
openvpn-gui --command connect $config 

openvpn-gui --command disconnect $config
```
with 
```ps1
& "C:\Program Files\OpenVPN\bin\openvpn-gui.exe" --command connect $config 

& "C:\Program Files\OpenVPN\bin\openvpn-gui.exe" --command disconnect $config 
```
Don't forget the `&`

**Comment by 7OH** [comment]
Yes. Spend an hour to find this needed & )))
