### ISSUE TITLE
Exit

### ISSUE THREAD

**Issue by 7OH** [T3los/mRemoteNGOpenVPN#2]
after writting words
"Initialization Sequence Completed "
script didnot exit

**Comment by T3los** [comment]
Hello again mate :)

By default, if the script found the log, then it will exit if the text  `,CONNECTED,SUCCESS` appears.
Can you check your OpenVPN connection log and tell me what is the text used to indicate a successful connection ?
I will add it in the script.

**Comment by 7OH** [comment]
"2022-08-01 09:17:03 Initialization Sequence Completed"
Here is last line on log

**Comment by T3los** [comment]
I added your txt to trigger the exit. Can you tell me if it is working ?

I have a update planned where i will add a variable to add trigger word.

**Comment by 7OH** [comment]
Thanks. Now it works
